/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'error-container': '#ffdad6',
        'on-secondary-fixed-variant': '#38485d',
        'outline-variant': '#c4c7c7',
        'surface-container-lowest': '#ffffff',
        'tertiary-fixed-dim': '#c4c7c9',
        'primary-fixed-dim': '#c8c6c5',
        'on-background': '#1a1c1c',
        'primary-fixed': '#e5e2e1',
        'inverse-on-surface': '#f0f1f1',
        'surface-container-low': '#f3f3f4',
        'on-primary-fixed-variant': '#474646',
        'on-secondary': '#ffffff',
        'tertiary-container': '#191c1e',
        'secondary-fixed-dim': '#b7c8e1',
        'primary-container': '#1c1b1b',
        'on-primary-container': '#858383',
        'on-error-container': '#93000a',
        tertiary: '#000000',
        'on-primary-fixed': '#1c1b1b',
        background: '#f9f9f9',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed-variant': '#444749',
        'on-tertiary-fixed': '#191c1e',
        surface: '#f9f9f9',
        'surface-bright': '#f9f9f9',
        'on-secondary-fixed': '#0b1c30',
        'surface-container': '#eeeeee',
        'on-secondary-container': '#54647a',
        error: '#ba1a1a',
        outline: '#747878',
        'on-surface-variant': '#444748',
        'inverse-primary': '#c8c6c5',
        'on-surface': '#1a1c1c',
        'surface-dim': '#dadada',
        'surface-tint': '#5f5e5e',
        'secondary-fixed': '#d3e4fe',
        'tertiary-fixed': '#e0e3e5',
        primary: '#000000',
        'on-primary': '#ffffff',
        'inverse-surface': '#2f3131',
        'on-error': '#ffffff',
        'secondary-container': '#d0e1fb',
        'surface-variant': '#e2e2e2',
        'on-tertiary-container': '#818486',
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e2e2e2',
        secondary: '#505f76',
        slate: {
          50: '#F8FAFC',
          200: '#E2E8F0',
        },
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '32px',
        'margin-mobile': '20px',
        unit: '4px',
        'margin-desktop': '64px',
        'section-gap': '128px',
        'container-max': '1280px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        sans: ['Geist', 'system-ui', 'sans-serif'],
        'display-lg': ['Geist', 'system-ui', 'sans-serif'],
        'label-caps': ['Geist', 'system-ui', 'sans-serif'],
        'display-lg-mobile': ['Geist', 'system-ui', 'sans-serif'],
        'mono-data': ['Geist Mono', 'ui-monospace', 'monospace'],
        'headline-sm': ['Geist', 'system-ui', 'sans-serif'],
        'body-lg': ['Geist', 'system-ui', 'sans-serif'],
        'headline-md': ['Geist', 'system-ui', 'sans-serif'],
        'body-md': ['Geist', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': [
          '72px',
          { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '600' },
        ],
        'label-caps': [
          '12px',
          { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '600' },
        ],
        'display-lg-mobile': [
          '40px',
          { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' },
        ],
        'mono-data': [
          '14px',
          { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' },
        ],
        'headline-sm': [
          '24px',
          { lineHeight: '1.4', letterSpacing: '-0.01em', fontWeight: '500' },
        ],
        'body-lg': [
          '18px',
          { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' },
        ],
        'headline-md': [
          '32px',
          { lineHeight: '1.3', letterSpacing: '-0.02em', fontWeight: '500' },
        ],
        'body-md': [
          '16px',
          { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' },
        ],
        'body-sm': [
          '14px',
          { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' },
        ],
      },
    },
  },
  plugins: [],
}
